---
- name: Download Helm Chart tarball
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/IBM/charts/master/repo/ibm-helm/ibm-b2bi-prod-{{ versions[b2bi_version].helm_chart_version }}.tgz"
    dest: ../output/{{ b2bi_namespace }}/ibm-b2bi-prod-{{ versions[b2bi_version].helm_chart_version }}.tgz
    mode: "0666"

- name: "Lookup Route from 'openshift-console' if provided"
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Route
    name: "console"
    namespace: "openshift-console"
  register: oc_route_cout

- name: Get subdomain of openshift cluster
  ansible.builtin.set_fact:
    openshift_host: "{{ oc_route_cout.resources[0].spec.host | regex_replace('.*console-openshift-console\\.', '') }}"

- name: Template values.yaml for reusability
  ansible.builtin.template:
    src: templates/values.yml.j2
    dest: ../output/{{ b2bi_namespace }}/values.yml
    mode: '0644'

- name: Deploy B2Bi helm Chart
  kubernetes.core.helm:
    name: "{{ b2bi_helm_release_name }}"
    chart_ref: ../output/{{ b2bi_namespace }}/ibm-b2bi-prod-{{ versions[b2bi_version].helm_chart_version }}.tgz
    release_namespace: "{{ b2bi_namespace }}"
    timeout: "4h"
    values_files:
      - ../output/{{ b2bi_namespace }}/values.yml
