---
ssp_engine_release_name: auto-eng
ssp_engine_version: 6.2.0.1.02
ssp_engine_license_type: non-prod

ssp_engine_namespace: ssp
ssp_cm_namespace: ssp


ssp_engine_generate_certificates: false
ssp_engine_registry_secret: ibm-entitlement-key
ssp_engine_secret: ibm-ssp-engine-secret
ssp_engine_registry: cp.icr.io
ssp_engine_registry_user: cp
ssp_engine_registry_key:
ssp_engine_serviceaccount: ssp-engine-sa
ssp_engine_pvc: ibm-ssp-engine-pvc

ssp_engine_sys_passphrase: Passw0rd@123
ssp_engine_keycert_store_passphrase: password
ssp_engine_keycert_encrypt_passphrase: password
ssp_engine_keycert_secret: "cm-keycert"
ssp_engine_custom_keycert_passphrase: password

versions:
  6.2.0.1.02:
    helm_chart_version: 1.5.4
