db2_version: s11.5.9.0-cn3
db2_channel: v110509.0

db2_namespace: db2

db2_registry_secret: ibm-registry-secret
registry: cp.icr.io
registry_user: cp

db2_secret: db2-secret
db2_service_account: db2-sa

db2_crd_name: db2
db2_username: db2inst1
db2_password: passw0rd
db2_dbname: BLUDB
db2_storage_size: 100Gi
